apiVersion: v1
kind: Secret
metadata:
  name: pg-user-credentials-demo
  namespace: observability-demo
  labels:
    cnpg.io/reload: 'true'
stringData:
  username: observability-demo-pg-username
  password: observability-demo-pg-password
  database: app
  host: cnpg-cluster-demo-rw.observability-demo
  port: '5432'
type: kubernetes.io/basic-auth
