apiVersion: v1
kind: Secret
metadata:
  name: strapi-credentials-demo
  namespace: observability-demo
stringData:
  DATABASE_CLIENT: postgres
  DATABASE_HOST: cnpg-cluster-demo-rw.observability-demo
  DATABASE_PORT: '5432'
  DATABASE_NAME: app
  APP_KEYS: <your-app-keys> # Adjust this to match your app keys
  ADMIN_JWT_SECRET: <your-admin-jwt-secret> # Adjust this to match your admin JWT secret
  TRANSFER_TOKEN_SALT: <your-transfer-token-salt> # Adjust this to match your transfer token salt
  ENCRYPTION_KEY: <your-encryption-key> # Adjust this to match your encryption key
