apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-instance-demo
  namespace: observability-demo
spec:
  image: jaegertracing/jaeger:latest
  ports:
    - name: jaeger
      port: 16686
  config:
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [jaeger_storage_exporter, debug]
    extensions:
      jaeger_query:
        storage:
          traces: memstore
      jaeger_storage:
        backends:
          memstore:
            memory:
              max_traces: 100000
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 600ms
        send_batch_size: 500
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 256
    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore
      debug:
        verbosity: detailed # verbosity can be 'basic', 'normal', or 'detailed'
