apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-uploads-demo
  namespace: observability-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: vultr-block-storage-hdd # Adjust this to match your storage class
