apiVersion: v1
kind: Service
metadata:
  name: strapi-app-service-demo
  namespace: observability-demo
  labels:
    app.kubernetes.io/name: strapi-app-demo
spec:
  ports:
    - port: 80
      name: http
      targetPort: 1337
      protocol: TCP
    - port: 9000
      name: prometheus
      targetPort: 9000
  selector:
    app: strapi-app-demo
